name: Build and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - unstable

jobs:
  build:
    name: Build and Publish on amd64
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        run: docker buildx create --use

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/lilkidsuave/cosmos-server:latest
          platforms: linux/amd64
